{ den, ... }:
{
  den.aspects.common.includes = [
    den.aspects.agenix
    den.aspects.audio
    den.aspects.bluetooth
    den.aspects.browser
    den.aspects.btrfs
    den.aspects.btop
    den.aspects.cache
    den.aspects.dev
    den.aspects."disko-btrfs"
    den.aspects.fastfetch
    den.aspects.file
    den.aspects.fish
    den.aspects.floorp
    den.aspects.fonts
    den.aspects.git
    den.aspects.hyprland
    den.aspects.impermanence
    den.aspects.keyboard
    den.aspects.kitty
    den.aspects.locale
    den.aspects.location
    den.aspects.optimizations
    den.aspects.packages
    den.aspects.sddm
    den.aspects.security.general
    den.aspects.security.kernel
    den.aspects.security.network
    den.aspects.security.ssh
    den.aspects.security.systemd
    den.aspects.syncthing
    den.aspects.theme
    den.aspects.user
    den.aspects.vesktop
    den.aspects.virtualization
    den.aspects.vscode
    den.aspects."xdg-dirs"
    den.aspects.yazi
    den.aspects.zed
  ];
}
