# hyprpaper.conf

source = ~/.config/hypr/constants.conf

ipc = on
splash = false

# Probably a more efficient way to do this
# Will check docs later

# Desktop
wallpaper {
    monitor = DP-2
    path = ~/nixos/assets/wallpapers/mornye.png
}

wallpaper {
    monitor = DP-3
    path = ~/nixos/assets/wallpapers/mornye.png
}

# Laptop
wallpaper {
    monitor = eDP-1
    path = ~/nixos/assets/wallpapers/mornye.png
}
