[config]

[templates.btop]
input_path = '~/nixos/config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.dunst]
input_path = '~/nixos/config/matugen/templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.gtk3]
input_path = '~/nixos/config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/nixos/config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.heroic]
input_path = '~/nixos/config/matugen/templates/heroic.css'
output_path = '~/.config/heroic/themes/matugen.css'

[templates.hyprland]
input_path = '~/nixos/config/matugen/templates/hypr.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/nixos/config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.prismlauncher]
input_path = '~/nixos/config/matugen/templates/prismlauncher.json'
output_path = '~/.local/share/PrismLauncher/themes/Matugen/theme.json'

[templates.quickshell]
input_path = '~/nixos/config/matugen/templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

[templates.vesktop]
input_path = '~/nixos/config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord-matugen.css'

[templates.vivaldi]
input_path = '~/nixos/config/matugen/templates/vivaldi.css'
output_path = '~/.config/vivaldi/themes/matugen.css'

[templates.yazi]
input_path = '~/nixos/config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zed]
input_path = '~/nixos/config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'
