exec-once = [workspace name:steam silent] steam
exec-once = [workspace name:games silent] heroic
exec-once = [workspace name:games silent] flatpak run moe.launcher.sleepy-launcher
exec-once = [workspace name:anime silent] vivaldi
