exec-once = quickshell -p /home/weeb/nixos/config/quickshell/bar
exec-once = blueman-applet & nm-applet
exec-once = protonvpn-app
exec-once = fcitx5
exec-once = hyprpaper & hypridle & hyprsunset & hyprshot

# exec-once = [workspace name:browser silent] brave
exec-once = [workspace name:vscode silent] code /home/weeb/nixos
exec-once = [workspace name:terminal silent] kitty
exec-once = [workspace name:spotify silent] spotify
exec-once = [workspace name:discord silent] vesktop
