# See https://wiki.hyprland.org/Configuring/Monitors/

source = ~/.config/hypr/constants.conf

# Desktop
monitorv2 {
  output = $mainMonitor
  mode = 3840x2160@60
  position = 0x0
  scale = 1.875
  bitdepth = 10
}
monitorv2 {
  output = $verticalMonitor
  mode = 2560x1440@60
  position = 2048x0
  scale = 1.33
  transform = 3
  bitdepth = 10
}

# Laptop
monitorv2 {
  output = eDP-1
  mode = highres@highrr
  position = 0x0
  scale = 1.25
}
